// <auto-generated />
using System;
using APIGestiónUsuarios.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGestiónUsuarios.Migrations
{
    [DbContext(typeof(GestionUsuariosContext))]
    partial class GestionUsuariosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIGestiónUsuarios.Models.Rol", b =>
                {
                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("APIGestiónUsuarios.Models.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UsuarioApellido")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UsuarioContraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UsuarioFechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UsuarioFechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("APIGestiónUsuarios.Models.UsuarioRol", b =>
                {
                    b.Property<Guid>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioRolId");

                    b.ToTable("UsuarioRol", (string)null);
                });

            modelBuilder.Entity("APIGestiónUsuarios.Models.Rol", b =>
                {
                    b.HasOne("APIGestiónUsuarios.Models.UsuarioRol", "UsuarioRol")
                        .WithOne("Rol")
                        .HasForeignKey("APIGestiónUsuarios.Models.Rol", "RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("APIGestiónUsuarios.Models.Usuario", b =>
                {
                    b.HasOne("APIGestiónUsuarios.Models.UsuarioRol", "UsuarioRol")
                        .WithOne("Usuario")
                        .HasForeignKey("APIGestiónUsuarios.Models.Usuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UsuarioRol");
                });

            modelBuilder.Entity("APIGestiónUsuarios.Models.UsuarioRol", b =>
                {
                    b.Navigation("Rol")
                        .IsRequired();

                    b.Navigation("Usuario")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
